theme: minima
title: My Epic Blog
author: shizzlefries
email: fanaticraincloud@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey I am an epic person, I hope I can share ablsolutely nothing through this blog post

# social links
twitter_username: shizlefries # DO NOT include the @ character, or else the build will fail!
github_username: shizzlefries # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
